import React, { useState } from 'react';
import { Mail, Copy, Calendar, FileText } from 'lucide-react';
import { useApp } from '../context/AppContext';

const DailyReportsView: React.FC = () => {
  const { tasks, milestones, documents, photos } = useApp();
  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0]);
  const [email, setEmail] = useState('');
  const [reportType, setReportType] = useState<'daily' | 'weekly'>('daily');
  const [reportText, setReportText] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  const generateReport = async () => {
    setIsGenerating(true);
    
    // Simulate AI report generation
    setTimeout(() => {
      const date = new Date(selectedDate);
      const dateStr = date.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
      
      const dayTasks = tasks.filter(t => t.date === selectedDate);
      const completedTasks = dayTasks.filter(t => t.completed);
      const pendingTasks = dayTasks.filter(t => !t.completed);
      
      let report = '';
      
      if (reportType === 'daily') {
        report = `DAILY CONSTRUCTION REPORT
Date: ${dateStr}

PROJECT SUMMARY
${milestones.length} milestone(s) in progress
${documents.length} document(s) on file
${photos.length} photo(s) captured

TASKS COMPLETED (${completedTasks.length})
${completedTasks.map(t => `✓ ${t.name} - ${t.category} (${t.crew || 'Unassigned'})`).join('\n') || 'No tasks completed today'}

TASKS PENDING (${pendingTasks.length})
${pendingTasks.map(t => `○ ${t.name} - ${t.category} (${t.crew || 'Unassigned'})`).join('\n') || 'No pending tasks'}

PRIORITY ITEMS
${pendingTasks.filter(t => t.priority === 'High').map(t => `⚠ ${t.name}`).join('\n') || 'No high priority items'}

NOTES
${dayTasks.map(t => t.notes).filter(n => n).join('\n') || 'No additional notes'}

---
Generated by AI Construction Assistant
`;
      } else {
        const weekStart = new Date(selectedDate);
        weekStart.setDate(weekStart.getDate() - weekStart.getDay());
        const weekEnd = new Date(weekStart);
        weekEnd.setDate(weekEnd.getDate() + 6);
        
        const weekTasks = tasks.filter(t => {
          const taskDate = new Date(t.date);
          return taskDate >= weekStart && taskDate <= weekEnd;
        });
        
        report = `WEEKLY CONSTRUCTION REPORT
Week of: ${weekStart.toLocaleDateString()} - ${weekEnd.toLocaleDateString()}

PROJECT OVERVIEW
${milestones.length} milestone(s) tracked
${documents.length} document(s) on file
${weekTasks.length} task(s) this week

WEEKLY SUMMARY
Completed Tasks: ${weekTasks.filter(t => t.completed).length}
Pending Tasks: ${weekTasks.filter(t => !t.completed).length}
High Priority Items: ${weekTasks.filter(t => t.priority === 'High' && !t.completed).length}

MILESTONES STATUS
${milestones.map(m => `• ${m.title}: ${new Date(m.startDate).toLocaleDateString()} - ${new Date(m.endDate).toLocaleDateString()}`).join('\n') || 'No milestones'}

TASK BREAKDOWN BY CATEGORY
${['General', 'Plumbing', 'Electrical', 'Framing', 'Concrete', 'Roofing'].map(cat => {
  const catTasks = weekTasks.filter(t => t.category === cat);
  return catTasks.length > 0 ? `${cat}: ${catTasks.length} task(s)` : null;
}).filter(Boolean).join('\n') || 'No tasks by category'}

---
Generated by AI Construction Assistant
`;
      }
      
      setReportText(report);
      setIsGenerating(false);
    }, 2000);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(reportText);
    alert('Report copied to clipboard!');
  };

  const handleEmail = () => {
    if (!email) {
      alert('Please enter an email address');
      return;
    }
    const mailtoLink = `mailto:${email}?subject=Construction ${reportType === 'daily' ? 'Daily' : 'Weekly'} Report - ${selectedDate}&body=${encodeURIComponent(reportText)}`;
    window.location.href = mailtoLink;
  };

  return (
    <div className="pb-20 min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white shadow-sm sticky top-0 z-10">
        <div className="px-4 py-4">
          <h1 className="text-2xl font-bold text-gray-900">Daily Reports</h1>
          <p className="text-sm text-gray-500 mt-1">AI-generated project reports</p>
        </div>
      </div>

      {/* Report Generation Controls */}
      <div className="px-4 mt-4 space-y-4">
        <div className="bg-white rounded-3xl shadow-sm p-4 space-y-3">
          <div className="flex gap-2">
            <button
              onClick={() => setReportType('daily')}
              className={`flex-1 py-2 px-4 rounded-xl font-medium transition-all ${
                reportType === 'daily'
                  ? 'bg-accent-purple text-white shadow-sm'
                  : 'bg-gray-100 text-gray-700'
              }`}
            >
              Daily
            </button>
            <button
              onClick={() => setReportType('weekly')}
              className={`flex-1 py-2 px-4 rounded-xl font-medium transition-all ${
                reportType === 'weekly'
                  ? 'bg-accent-purple text-white shadow-sm'
                  : 'bg-gray-100 text-gray-700'
              }`}
            >
              Weekly
            </button>
          </div>
          
          <div className="flex items-center gap-2">
            <Calendar size={20} className="text-gray-400" />
            <input
              type="date"
              value={selectedDate}
              onChange={(e) => setSelectedDate(e.target.value)}
              className="flex-1 px-4 py-3 rounded-xl border border-gray-200 focus:outline-none focus:ring-2 focus:ring-accent-purple"
            />
          </div>
          
          <input
            type="email"
            placeholder="Email address (optional)"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:outline-none focus:ring-2 focus:ring-accent-purple"
          />
          
          <button
            onClick={generateReport}
            disabled={isGenerating}
            className="w-full bg-accent-purple text-white py-4 rounded-xl font-medium shadow-sm hover:shadow-md transition-shadow disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
          >
            <FileText size={20} />
            <span>{isGenerating ? 'Generating Report...' : `Generate & Email ${reportType === 'daily' ? 'Daily' : 'Weekly'} Report`}</span>
          </button>
        </div>

        {/* Report Text Box */}
        {reportText && (
          <div className="bg-white rounded-3xl shadow-sm p-4">
            <div className="flex items-center justify-between mb-3">
              <h2 className="font-semibold text-gray-900">Generated Report</h2>
              <div className="flex gap-2">
                <button
                  onClick={copyToClipboard}
                  className="p-2 text-gray-400 hover:text-blue-500"
                  title="Copy to clipboard"
                >
                  <Copy size={18} />
                </button>
                <button
                  onClick={handleEmail}
                  className="p-2 text-gray-400 hover:text-green-500"
                  title="Email report"
                >
                  <Mail size={18} />
                </button>
              </div>
            </div>
            <textarea
              value={reportText}
              onChange={(e) => setReportText(e.target.value)}
              rows={15}
              className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:outline-none focus:ring-2 focus:ring-accent-purple resize-none font-mono text-sm"
              placeholder="Generated report will appear here..."
            />
          </div>
        )}
      </div>
    </div>
  );
};

export default DailyReportsView;
